name: OIDC-TEST

on: push

permissions:
  id-token: write # Required for requesting the AWS JWT

jobs:
  build-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for OIDC
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: OIDC-Session

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity
